"""character improvements

Revision ID: 020b9b3d768d
Revises: 8300cda1f785
Create Date: 2026-03-14 09:34:31.349656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '020b9b3d768d'
down_revision: Union[str, Sequence[str], None] = '8300cda1f785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('current_location_id', sa.BigInteger(), nullable=True))
    op.alter_column('characters', 'role',
               existing_type=postgresql.ENUM('IDOL', 'ACTOR', 'MANGAKA', 'EDITOR', 'WRITER', 'AGENT', 'LAWYER', 'MEDICINE', 'STYLIST', 'MAFIA', name='roles'),
               nullable=False)
    op.alter_column('characters', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index(op.f('ix_characters_agency_id'), 'characters', ['agency_id'], unique=False)
    op.create_index('ix_uq_characters_one_active_per_user', 'characters', ['user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_uq_characters_one_in_location_per_user', 'characters', ['user_id'], unique=True, postgresql_where=sa.text('current_location_id IS NOT NULL'))
    op.create_unique_constraint('uq_characters_user_id_name', 'characters', ['user_id', 'name'])
    op.create_foreign_key(
        'fk_characters_agency_id_agencies',
        'characters',
        'agencies',
        ['agency_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.drop_column('characters', 'entranced_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('entranced_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_characters_agency_id_agencies', 'characters', type_='foreignkey')
    op.create_foreign_key(op.f('characters_agency_id_fkey'), 'characters', 'agencies', ['agency_id'], ['id'])
    op.drop_constraint('uq_characters_user_id_name', 'characters', type_='unique')
    op.drop_index('ix_uq_characters_one_in_location_per_user', table_name='characters', postgresql_where=sa.text('current_location_id IS NOT NULL'))
    op.drop_index('ix_uq_characters_one_active_per_user', table_name='characters', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_characters_agency_id'), table_name='characters')
    op.alter_column('characters', 'birthday',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('characters', 'role',
               existing_type=postgresql.ENUM('IDOL', 'ACTOR', 'MANGAKA', 'EDITOR', 'WRITER', 'AGENT', 'LAWYER', 'MEDICINE', 'STYLIST', 'MAFIA', name='roles'),
               nullable=True)
    op.drop_column('characters', 'current_location_id')
    # ### end Alembic commands ###
