"""Vote entity primary key by char id and voted by

Revision ID: 06acfe8b764f
Revises: 1a0cdc2b01ad
Create Date: 2026-05-02 21:39:21.970072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06acfe8b764f'
down_revision: Union[str, Sequence[str], None] = '1a0cdc2b01ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
