"""change cooldown to a states

Revision ID: 159de1ebb373
Revises: c1afcc0feb79
Create Date: 2026-03-30 06:09:26.689832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '159de1ebb373'
down_revision: Union[str, Sequence[str], None] = 'c1afcc0feb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('step', sa.Enum('WELCOME', 'INTRO', 'RULES', 'DRAFT_REGISTRATION', 'FULL_REGISTRATION', 'COMPLETED', name='onboardingstep', native_enum=False), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_events_user_id'), 'onboarding_events', ['user_id'], unique=False)
    op.create_table('onboarding_role_grants',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('onboarding_states',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('current_step', sa.Enum('WELCOME', 'INTRO', 'RULES', 'DRAFT_REGISTRATION', 'FULL_REGISTRATION', 'COMPLETED', name='onboardingstep', native_enum=False), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('characters', sa.Column('entranced_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('characters', sa.Column('last_exposed_at', sa.DateTime(), nullable=True))
    op.alter_column('characters', 'role',
               existing_type=postgresql.ENUM('IDOL', 'ACTOR', 'MANGAKA', 'EDITOR', 'WRITER', 'AGENT', 'LAWYER', 'MEDICINE', 'STYLIST', 'MAFIA', name='roles'),
               nullable=True)
    op.alter_column('characters', 'birthday',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_characters_agency_id'), table_name='characters')
    op.drop_index(op.f('ix_uq_characters_one_active_per_user'), table_name='characters', postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_uq_characters_one_in_location_per_user'), table_name='characters', postgresql_where='(current_location_id IS NOT NULL)')
    op.drop_constraint(op.f('uq_characters_user_id_name'), 'characters', type_='unique')
    op.drop_constraint(op.f('characters_agency_id_fkey'), 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'agencies', ['agency_id'], ['id'])
    op.drop_column('characters', 'current_location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('current_location_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(op.f('characters_agency_id_fkey'), 'characters', 'agencies', ['agency_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_characters_user_id_name'), 'characters', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_uq_characters_one_in_location_per_user'), 'characters', ['user_id'], unique=True, postgresql_where='(current_location_id IS NOT NULL)')
    op.create_index(op.f('ix_uq_characters_one_active_per_user'), 'characters', ['user_id'], unique=True, postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_characters_agency_id'), 'characters', ['agency_id'], unique=False)
    op.alter_column('characters', 'birthday',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('characters', 'role',
               existing_type=postgresql.ENUM('IDOL', 'ACTOR', 'MANGAKA', 'EDITOR', 'WRITER', 'AGENT', 'LAWYER', 'MEDICINE', 'STYLIST', 'MAFIA', name='roles'),
               nullable=False)
    op.drop_column('characters', 'last_exposed_at')
    op.drop_column('characters', 'entranced_channel_id')
    op.drop_table('onboarding_states')
    op.drop_table('onboarding_role_grants')
    op.drop_index(op.f('ix_onboarding_events_user_id'), table_name='onboarding_events')
    op.drop_table('onboarding_events')
    # ### end Alembic commands ###
