"""Vote entity fix (index by voted_by & character_id)

Revision ID: 1a0cdc2b01ad
Revises: 2592a0d70290
Create Date: 2026-05-02 21:38:22.609623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0cdc2b01ad'
down_revision: Union[str, Sequence[str], None] = '2592a0d70290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
