"""onboarding_states (fix import)

Revision ID: 4693de62dd83
Revises: 63cbc8e309e9
Create Date: 2026-04-11 10:11:40.335721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4693de62dd83'
down_revision: Union[str, Sequence[str], None] = '63cbc8e309e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('step', sa.Enum('WELCOME', 'INTRO', 'RULES', 'DRAFT_REGISTRATION', 'FULL_REGISTRATION', 'COMPLETED', name='onboardingstep', native_enum=False), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_events_user_id'), 'onboarding_events', ['user_id'], unique=False)
    op.create_table('onboarding_role_grants',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('onboarding_states',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('current_step', sa.Enum('WELCOME', 'INTRO', 'RULES', 'DRAFT_REGISTRATION', 'FULL_REGISTRATION', 'COMPLETED', name='onboardingstep', native_enum=False), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index(op.f('ix_agencies_id'), table_name='agencies')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_constraint(op.f('fk_characters_agency_id_agencies'), 'characters', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_characters_agency_id_agencies'), 'characters', 'agencies', ['agency_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_agencies_id'), 'agencies', ['id'], unique=False)
    op.drop_table('onboarding_states')
    op.drop_table('onboarding_role_grants')
    op.drop_index(op.f('ix_onboarding_events_user_id'), table_name='onboarding_events')
    op.drop_table('onboarding_events')
    # ### end Alembic commands ###
