"""return DateTime(timezone=True) in Character

Revision ID: 493e2ed0deef
Revises: adae3eff76b0
Create Date: 2026-03-31 15:56:25.705862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493e2ed0deef'
down_revision: Union[str, Sequence[str], None] = 'adae3eff76b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
