"""remove home_channel_id for Character

Revision ID: 585f0a42452b
Revises: 75ac26b2468b
Create Date: 2026-04-23 16:06:56.651160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585f0a42452b'
down_revision: Union[str, Sequence[str], None] = '75ac26b2468b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('biography', sa.String(), nullable=False))
    op.drop_column('characters', 'home_channel_id')
    op.alter_column('onboarding_events', 'step',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.Enum('NEWBIE', 'WELCOME', 'INTRO', 'RULES', 'REGISTRATION', 'COMPLETED', name='onboardingstep', native_enum=False),
               existing_nullable=True)
    op.alter_column('onboarding_states', 'current_step',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.Enum('NEWBIE', 'WELCOME', 'INTRO', 'RULES', 'REGISTRATION', 'COMPLETED', name='onboardingstep', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('onboarding_states', 'current_step',
               existing_type=sa.Enum('NEWBIE', 'WELCOME', 'INTRO', 'RULES', 'REGISTRATION', 'COMPLETED', name='onboardingstep', native_enum=False),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
    op.alter_column('onboarding_events', 'step',
               existing_type=sa.Enum('NEWBIE', 'WELCOME', 'INTRO', 'RULES', 'REGISTRATION', 'COMPLETED', name='onboardingstep', native_enum=False),
               type_=sa.VARCHAR(length=18),
               existing_nullable=True)
    op.add_column('characters', sa.Column('home_channel_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('characters', 'biography')
    # ### end Alembic commands ###
