"""subscriptions

Revision ID: 5b0c68059f04
Revises: 8f2a6d0e7b41
Create Date: 2026-06-21 14:49:25.204719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b0c68059f04'
down_revision: Union[str, Sequence[str], None] = '8f2a6d0e7b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('character_author_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('followed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('characters', 'role',
               existing_type=postgresql.ENUM('IDOL', 'ACTOR', 'MANGAKA', 'EDITOR', 'WRITER', 'AGENT', 'LAWYER', 'MEDICINE', 'STYLIST', 'MAFIA', name='roles'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'role',
               existing_type=postgresql.ENUM('IDOL', 'ACTOR', 'MANGAKA', 'EDITOR', 'WRITER', 'AGENT', 'LAWYER', 'MEDICINE', 'STYLIST', 'MAFIA', name='roles'),
               nullable=True)
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
