"""Add character gender

Revision ID: bba674f15f69
Revises: dbfdff6744e3
Create Date: 2026-09-09 20:05:00.343641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba674f15f69'
down_revision: Union[str, Sequence[str], None] = 'dbfdff6744e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

charactergender_enum = sa.Enum('MALE', 'FEMALE', name='charactergender')

def upgrade() -> None:
    """Upgrade schema."""
    charactergender_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('gender', charactergender_enum, nullable=False))
    op.alter_column('characters', 'gender', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'gender')
    charactergender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
