"""Role field in Character accept other role enums

Revision ID: dcc1e200d5fe
Revises: 4deb798e8aa9
Create Date: 2026-05-02 20:22:24.795684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc1e200d5fe'
down_revision: Union[str, Sequence[str], None] = '4deb798e8aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('entered_channel_id', sa.BigInteger(), nullable=True))
    op.drop_column('characters', 'entranced_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('entranced_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('characters', 'entered_channel_id')
    # ### end Alembic commands ###
